from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="book-index"),
    path("index2/<int:val1>/", views.index2, name="book-index2"),
    path("search", views.searchbooks, name="book-search"),
    path("search/", views.searchbooks),
    path("simple/query", views.simple_query, name="simple-query"),
    path("simple/query/", views.simple_query),
    path("complex/query", views.complex_query, name="complex-query"),
    path("complex/query/", views.complex_query),
    path("lab8/", views.lab8_index, name="lab8-index"),
    path("lab8/task1", views.lab8_task1, name="lab8-task1"),
    path("lab8/task2", views.lab8_task2, name="lab8-task2"),
    path("lab8/task3", views.lab8_task3, name="lab8-task3"),
    path("lab8/task4", views.lab8_task4, name="lab8-task4"),
    path("lab8/task5", views.lab8_task5, name="lab8-task5"),
    path("lab8/task7", views.lab8_task7, name="lab8-task7"),
    path("lab9/", views.lab9_index, name="lab9-index"),
    path("lab9/task1", views.lab9_task1, name="lab9-task1"),
    path("lab9/task2", views.lab9_task2, name="lab9-task2"),
    path("lab9/task3", views.lab9_task3, name="lab9-task3"),
    path("lab9/task4", views.lab9_task4, name="lab9-task4"),
    path("lab9/task5", views.lab9_task5, name="lab9-task5"),
    path("lab9/task6", views.lab9_task6, name="lab9-task6"),
    path("html5/links", views.lab5_links, name="lab5-links"),
    path("html5/formatting", views.lab5_formatting, name="lab5-formatting"),
    path("html5/listing", views.lab5_listing, name="lab5-listing"),
    path("html5/tables", views.lab5_tables, name="lab5-tables"),
    path("<int:bookId>", views.viewbook, name="view-book"),
]
