from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="book-index"),
    path("index2/<int:val1>/", views.index2, name="book-index2"),
    path("search", views.searchbooks, name="book-search"),
    path("search/", views.searchbooks),
    path("simple/query", views.simple_query, name="simple-query"),
    path("simple/query/", views.simple_query),
    path("complex/query", views.complex_query, name="complex-query"),
    path("complex/query/", views.complex_query),
    path("lab8/", views.lab8_index, name="lab8-index"),
    path("lab8/task1", views.lab8_task1, name="lab8-task1"),
    path("lab8/task2", views.lab8_task2, name="lab8-task2"),
    path("lab8/task3", views.lab8_task3, name="lab8-task3"),
    path("lab8/task4", views.lab8_task4, name="lab8-task4"),
    path("lab8/task5", views.lab8_task5, name="lab8-task5"),
    path("lab8/task7", views.lab8_task7, name="lab8-task7"),
    path("lab9/", views.lab9_index, name="lab9-index"),
    path("lab9/task1", views.lab9_task1, name="lab9-task1"),
    path("lab9/task2", views.lab9_task2, name="lab9-task2"),
    path("lab9/task3", views.lab9_task3, name="lab9-task3"),
    path("lab9/task4", views.lab9_task4, name="lab9-task4"),
    path("lab9/task5", views.lab9_task5, name="lab9-task5"),
    path("lab9/task6", views.lab9_task6, name="lab9-task6"),
    path("lab10/", views.lab10_index, name="lab10-index"),
    path("lab9_part1/list_books", views.lab10_part1_list_books, name="lab10-part1-list"),
    path("lab9_part1/addbook", views.lab10_part1_add_book, name="lab10-part1-add"),
    path("lab9_part1/editbook/<int:book_id>", views.lab10_part1_edit_book, name="lab10-part1-edit"),
    path("lab9_part1/deletebook/<int:book_id>", views.lab10_part1_delete_book, name="lab10-part1-delete"),
    path("lab9_part2/list_books", views.lab10_part2_list_books, name="lab10-part2-list"),
    path("lab9_part2/addbook", views.lab10_part2_add_book, name="lab10-part2-add"),
    path("lab9_part2/editbook/<int:book_id>", views.lab10_part2_edit_book, name="lab10-part2-edit"),
    path("lab9_part2/deletebook/<int:book_id>", views.lab10_part2_delete_book, name="lab10-part2-delete"),
    path("lab11/", views.lab11_index, name="lab11-index"),
    path("lab11/task1/students", views.lab11_task1_list_students, name="lab11-task1-list"),
    path("lab11/task1/students/add", views.lab11_task1_add_student, name="lab11-task1-add"),
    path("lab11/task1/students/<int:student_id>/edit", views.lab11_task1_edit_student, name="lab11-task1-edit"),
    path("lab11/task1/students/<int:student_id>/delete", views.lab11_task1_delete_student, name="lab11-task1-delete"),
    path("lab11/task2/students", views.lab11_task2_list_students, name="lab11-task2-list"),
    path("lab11/task2/students/add", views.lab11_task2_add_student, name="lab11-task2-add"),
    path("lab11/task2/students/<int:student_id>/edit", views.lab11_task2_edit_student, name="lab11-task2-edit"),
    path("lab11/task2/students/<int:student_id>/delete", views.lab11_task2_delete_student, name="lab11-task2-delete"),
    path("lab11/task3/gallery", views.lab11_task3_list_gallery, name="lab11-task3-list"),
    path("lab11/task3/gallery/add", views.lab11_task3_add_gallery_item, name="lab11-task3-add"),
    path("html5/links", views.lab5_links, name="lab5-links"),
    path("html5/formatting", views.lab5_formatting, name="lab5-formatting"),
    path("html5/listing", views.lab5_listing, name="lab5-listing"),
    path("html5/tables", views.lab5_tables, name="lab5-tables"),
    path("<int:bookId>", views.viewbook, name="view-book"),
]
